Try fix amplification setup
Things now use the c4t binaries rather than the (dead) c4f stuff.

I've changed the default Memalloy setup to use partialSC instead of
RC11+noRMWs.  Hopefully this works out.

diff --git a/do_memalloy_amplify b/do_memalloy_amplify
--- a/do_memalloy_amplify
+++ b/do_memalloy_amplify
@@ -1,27 +1,37 @@
 #!/usr/bin/env bash
 #
 # A harness script that runs memalloy (looking for it in the given directory),
-# DNF-converts every result it generates, and outputs it into another given
+# amplifies every result it generates, and outputs it into another given
 # directory.
 
 set -euo pipefail
 
 SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
-# shellcheck source=scripts/act_bash/args.sh
+# shellcheck source=./act_bash/args.sh
 source "${SCRIPTDIR}/act_bash/args.sh"
-# shellcheck source=scripts/act_bash/exec.sh
+# shellcheck source=./act_bash/exec.sh
 source "${SCRIPTDIR}/act_bash/exec.sh"
-# shellcheck source=scripts/act_bash/log.sh
+# shellcheck source=./act_bash/log.sh
 source "${SCRIPTDIR}/act_bash/log.sh"
 
 declare DEFAULT_MEMALLOY_EVENTS ACT_STANDARD_FLAGS ACT_STANDARD_OPTS
-# shellcheck source=scripts/act_bash/memalloy.sh
+# shellcheck source=./act_bash/memalloy.sh
 source "${SCRIPTDIR}/act_bash/memalloy.sh"
 
 ## Arguments ##
 
 
-# Whether we are using Dune to execute any OCaml ACT tools.
+# The architecture ID to use, if we're targeting a backend that needs it.
+# Can be empty.
+ARCH=""
+
+# The backend ID to use to get state sets.
+# Can be empty, in which case the first backend defined gets run.
+BACKEND=""
+
+# TODO(@MattWindsor91): eventually reinstate compiler-indirect amplification.
+
+# Whether we are using Dune to execute c4f.
 DUNE_EXEC="false"
 
 # Whether we are forcing Memalloy and DNF to run even if we have a results directory.
@@ -30,8 +40,8 @@ FORCE_MEMALLOY="false"
 # The directory in which Memalloy lives.
 MEMALLOY_DIR=""
 
-# The DNF output directory.
-DNF_DIR=""
+# The amplified output directory.
+AMP_DIR=""
 
 # The number of events to ask Memalloy to generate.
 # Defaults to `DEFAULT_MEMALLOY_EVENTS` if empty.
@@ -43,10 +53,13 @@ MEMALLOY_EVENTS=""
 # Prints usage information and exits.
 usage() {
   echo "Usage: $0"
-  echo "  [-e NUM_MEMALLOY_EVENTS]"
-  echo "  [-fsuwtnSUWTN${ACT_STANDARD_FLAGS}] MEMALLOY_DIR OUTPUT_DIR"
+  echo "  [-a ARCH] [-b BACKEND] [-e NUM_MEMALLOY_EVENTS]"
+  echo "  [-f${ACT_STANDARD_FLAGS}] MEMALLOY_DIR OUTPUT_DIR"
   echo
+  echo "-a: ID of architecture to use if the backend requires one"
+  echo "-b: ID of backend to use for checking C files"
   echo "-e: number of events for Memalloy to produce (default ${DEFAULT_MEMALLOY_EVENTS})"
+  echo "-f: force run of Memalloy even if MEMALLOY_DIR/results/_latest exists"
   act::standard_usage
   echo
   echo "OUTPUT_DIR will be created if needed, and MAY be a subdirectory of"
@@ -57,27 +70,32 @@ usage() {
 
 # Main function.
 main() {
-  while getopts "e:f${ACT_STANDARD_OPTS}" a; do
+  while getopts "a:b:e:f${ACT_STANDARD_OPTS}" a; do
     case ${a} in
+    a) ARCH="${OPTARG}" ;;
+    b) BACKEND="${OPTARG}" ;;
     e) MEMALLOY_EVENTS=${OPTARG} ;;
     f) FORCE_MEMALLOY="true" ;;
     *) act::parse_standard_args "${a}" "${OPTARG:-}" ;;
     esac
   done
-  readonly MEMALLOY_EVENTS FORCE_MEMALLOY DUNE_EXEC VERBOSE
+  readonly ARCH BACKEND MEMALLOY_EVENTS FORCE_MEMALLOY
+  # These are used indirectly by various library functions.
+  # shellcheck disable=SC2034
+  readonly DUNE_EXEC VERBOSE
   shift $((OPTIND-1))
 
   act::check_dune_exec
 
   if [[ $# -ne 2 ]]; then act::arg_error "need two directory arguments"; fi
   readonly MEMALLOY_DIR=$1
-  readonly DNF_DIR=$2
+  readonly AMP_DIR=$2
 
   local results_dir="${MEMALLOY_DIR}/results/_latest"
 
   run_memalloy_if_needed "${results_dir}"
 
-  run_dnf_if_needed "${results_dir}"
+  amplify_if_needed "${results_dir}"
 }
 
 
@@ -125,36 +143,36 @@ run_memalloy() {
 
 
 # Checks whether Memalloy forcing is on, or if the DNF directory is
-# not present.  If either are true, runs `make_dnf` for each result in
+# not present.  If either are true, runs `make_amp` for each result in
 # the results directory, outputting successful results to the
 # DNF directory.
 #
 # If we are reusing the existing Memalloy directory, and verbosity is on,
 #
 # Globals:
-#   DNF_DIR: read
+#   AMP_DIR: read
 #   FORCE_MEMALLOY: read
 #   (various others read indirectly)
 #
 # Arguments:
 #   1: the memalloy results directory.
-run_dnf_if_needed() {
+amplify_if_needed() {
   local results_dir="${1}"
 
-  if [[ ${FORCE_MEMALLOY} = "true" || ( ! -d "${DNF_DIR}" ) ]]; then
-    run_dnf "${results_dir}" "${DNF_DIR}"
+  if [[ ${FORCE_MEMALLOY} = "true" || ( ! -d "${AMP_DIR}" ) ]]; then
+    amplify "${results_dir}" "${AMP_DIR}"
   else
-    act::log "Using existing DNF directory"
-    dump_last_modified_time "${DNF_DIR}"
+    act::log "Using existing amplify directory"
+    dump_last_modified_time "${AMP_DIR}"
     act::log ".\n"
   fi
 
-  if [[ ! -d "${DNF_DIR}" ]]; then act::fatal "Missing DNF directory"; fi
+  if [[ ! -d "${AMP_DIR}" ]]; then act::fatal "Missing amplify directory"; fi
 }
 
 
-# Runs `make_dnf` on each test in the results directory, outputting the
-# results to the DNF directory.
+# Amplifies each test in the results directory, outputting the # results to the
+# given directory.
 #
 # Globals:
 #   SCRIPTDIR: read
@@ -162,23 +180,21 @@ run_dnf_if_needed() {
 #
 # Arguments:
 #   1: the memalloy results directory.
-#   2: the dnf output directory.
-run_dnf() {
+#   2: the amp output directory.
+amplify() {
   local results_dir="${1}"
-  local dnf_dir="${2}"
+  local amp_dir="${2}"
 
-  act::log "DNF-converting memalloy results.\n"
-  mkdir -p "${dnf_dir}"
-
-  local flags
-  flags="$(act::flags_qvx)"
+  act::log "Amplifying memalloy results.\n"
+  mkdir -p "${amp_dir}"
 
   for file in "${results_dir}/litmus"/*.litmus; do
     local out_file
-    out_file="${dnf_dir}/$(basename "${file}")"
+    out_file="${amp_dir}/$(basename "${file}")"
     act::log "~> %s (to %s)\n" "${file}" "${out_file}"
-    # TODO(@MattWindsor91): -b BACKEND
-    "${SCRIPTDIR}/make_dnf" "${flags}" "${file}" > "${out_file}" || broken_dnf "${out_file}"
+    act::run_with_qvx "${SCRIPTDIR}/amplify" \
+      -a "${ARCH}" -b "${BACKEND}" \
+      "${file}" > "${out_file}" || broken_amp "${out_file}"
   done
 }
 
@@ -192,9 +208,9 @@ run_dnf() {
 #
 # Arguments:
 #   1.  The file that failed postcondition conversion.
-broken_dnf() {
+broken_amp() {
   local file="$1"
-  local new_file="${file}.bad_dnf"
+  local new_file="${file}.bad_amp"
 
   act::error "Couldn't DNF postcondition for ${file}."
   act::error "Moving out of the way (to ${new_file})."
